"""Vault scaffolding and inspection helpers (Phase 10).

A *vault* is a private git repo containing one knowledge base's data tree
(`extracted/`, `manifests/`, `derived/`, `wiki/`, plus its own `config/`).
Code lives in the public `arquimedes` package, installed via pipx; vaults are
distinct repos pointed at via the global `--config` flag, the
`$ARQUIMEDES_CONFIG` env var, or cwd-walk.

This module owns:
- `init_vault()` — scaffold an empty vault on disk (no remote, no library).
- `vault_info()` — report the resolved vault root, library root, local cache
  root, freshness, config source, and vault git remote.
"""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path

_GITIGNORE = """\
# Per-machine runtime artifacts (regenerated by `arq refresh`)
indexes/
logs/
*.sqlite-shm
*.sqlite-wal

# Local config overrides (per machine)
config/config.local.yaml
config/collaborator/config.local.yaml
config/maintainer/config.local.yaml

# OS noise
.DS_Store
Thumbs.db
"""

_SHARED_CONFIG = """\
# Vault shared config (committed). Per-role overrides live under
# config/collaborator/config.local.yaml or config/maintainer/config.local.yaml.

# Path to the shared library folder (source PDFs). Override per-machine in
# config/maintainer/config.local.yaml or config/collaborator/config.local.yaml.
library_root: "~/Arquimedes-Library"

sync:
  pull_interval: 300
  auto_start: false
  auto_index: true
  reset_tracked: true

serve:
  host: "0.0.0.0"
  port: 8420
"""

_MAINTAINER_PROFILE = """\
# Maintainer profile for this vault. Presence of this file marks the machine
# as the vault's maintainer; freshness will not run destructive git restore
# here.

# Optional remote MCP profile for ChatGPT / other remote MCP clients.
# Configure this only on the maintainer machine that should publish the MCP.
#
# mcp:
#   transport: "streamable-http"
#   host: "127.0.0.1"
#   port: 8000
#   streamable_http_path: "/mcp"
#   keep_alive: true
#   auth:
#     issuer_url: "https://auth.example.com"
#     resource_server_url: "https://mcp.example.com/mcp"
#     required_scopes: ["arq.read"]
#     allowed_emails: ["you@example.com"]
#     # or, for an org vault:
#     # allowed_email_domains: ["yourorg.com"]
"""

_VAULT_SUBDIRS = ("extracted", "manifests", "derived", "wiki", "config")


class VaultExistsError(Exception):
    """Raised when `arq init <path>` is called on a non-empty target."""


@dataclass
class VaultInitResult:
    root: Path
    git_initialized: bool
    files_created: list[str]

    def to_dict(self) -> dict:
        return {
            "root": str(self.root),
            "git_initialized": self.git_initialized,
            "files_created": self.files_created,
        }


def clone_vault(remote_url: str, path: str | Path) -> VaultInitResult:
    """Clone an existing vault repo from `remote_url` into `path`.

    Used by collaborators on first onboarding. Refuses to clone over an
    existing non-empty directory. Does not write any local config — the
    collaborator overlay is added separately by `setup.md`.
    """
    target = Path(path).expanduser().resolve()
    if target.exists() and any(target.iterdir()):
        raise VaultExistsError(f"{target} already exists and is not empty.")
    target.parent.mkdir(parents=True, exist_ok=True)

    result = subprocess.run(
        ["git", "clone", remote_url, str(target)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout or "git clone failed").strip()
        raise RuntimeError(message)

    return VaultInitResult(
        root=target,
        git_initialized=True,
        files_created=[str(p.relative_to(target)) for p in sorted(target.iterdir()) if p.name != ".git"],
    )


def init_vault(path: str | Path, *, init_git: bool = True) -> VaultInitResult:
    """Scaffold an empty vault at `path`.

    Creates the standard subtree, a minimal `config/config.yaml`, a maintainer
    profile marker (so this machine becomes the vault's maintainer), an empty
    `manifests/materials.jsonl`, and a `.gitignore`. Optionally runs `git init`.

    Refuses to overwrite an existing non-empty directory.
    """
    root = Path(path).expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        raise VaultExistsError(f"{root} already exists and is not empty.")
    root.mkdir(parents=True, exist_ok=True)

    files_created: list[str] = []
    for sub in _VAULT_SUBDIRS:
        (root / sub).mkdir(parents=True, exist_ok=True)
    (root / "config" / "maintainer").mkdir(parents=True, exist_ok=True)

    def _write(rel: str, content: str) -> None:
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        files_created.append(rel)

    _write(".gitignore", _GITIGNORE)
    _write("config/config.yaml", _SHARED_CONFIG)
    _write("config/maintainer/config.yaml", _MAINTAINER_PROFILE)
    _write("manifests/materials.jsonl", "")

    git_initialized = False
    if init_git:
        result = subprocess.run(
            ["git", "init", "-q"],
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
        git_initialized = result.returncode == 0

    return VaultInitResult(root=root, git_initialized=git_initialized, files_created=files_created)


@dataclass
class VaultInfo:
    vault_root: Path
    library_root: Path | None
    local_cache_root: Path
    config_sources: list[Path]
    git_remote: str | None
    has_index: bool

    def to_dict(self) -> dict:
        return {
            "vault_root": str(self.vault_root),
            "library_root": str(self.library_root) if self.library_root else None,
            "local_cache_root": str(self.local_cache_root),
            "config_sources": [str(p) for p in self.config_sources],
            "git_remote": self.git_remote,
            "has_index": self.has_index,
        }


def vault_info() -> VaultInfo:
    """Resolve and return information about the active vault.

    Raises ``FileNotFoundError`` (with a helpful message) when no vault can be
    located via env var, cwd-walk, or installed-package fallback.
    """
    from arquimedes.config import (
        _config_stack,
        get_local_cache_root,
        get_vault_root,
        load_config,
    )
    from arquimedes.index import get_index_path

    vault_root = get_vault_root()
    config = load_config()
    library_root = Path(config["library_root"]) if "library_root" in config else None
    local_cache = get_local_cache_root(config)
    sources = _config_stack()

    git_remote: str | None = None
    result = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=vault_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode == 0:
        git_remote = result.stdout.strip() or None

    return VaultInfo(
        vault_root=vault_root,
        library_root=library_root,
        local_cache_root=local_cache,
        config_sources=sources,
        git_remote=git_remote,
        has_index=get_index_path(config).exists(),
    )


def format_vault_info_human(info: VaultInfo) -> str:
    lines = [
        f"vault_root:       {info.vault_root}",
        f"library_root:     {info.library_root or '(unset)'}",
        f"local_cache_root: {info.local_cache_root}",
        f"git_remote:       {info.git_remote or '(none)'}",
        f"index_present:    {'yes' if info.has_index else 'no'}",
        "config_sources:",
    ]
    for src in info.config_sources:
        lines.append(f"  - {src}")
    return "\n".join(lines)


__all__ = [
    "VaultExistsError",
    "VaultInfo",
    "VaultInitResult",
    "clone_vault",
    "format_vault_info_human",
    "init_vault",
    "vault_info",
]
